name: Native bench

on:
  workflow_dispatch:
    inputs:
      cpu_tag:
        description: "CPU type for job"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - E5645

jobs:
  run-benchmark:
    name: bench swim.json - seed 8780830896941405304 - Early termination
    runs-on: ${{ inputs.cpu_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rust-src

      - name: Run bench
        env:
          RUSTFLAGS: "-C target-cpu=native -Awarnings"
        run: |
          cd sparrow
          export RUSTFLAGS=$RUSTFLAGS
          output=$(cargo run --profile release --features=only_final_svg,simd --bin bench-wasm -- ./data/input/swim.json | tee /dev/stderr)
          echo "$output" > "output/bench_native.log"
          {
            echo "## Benchmark Output for swim.json"
            echo '```'
            echo "$output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Commit and push benchmark results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update benchmark results"
          file_pattern: "results/benchmark_results_native.csv"
